# Generated by Django 5.1.1 on 2024-10-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0002_user_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('staff', 'Staff')], default='student', max_length=10)),
                ('food_category', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
