# Generated by Django 5.1.1 on 2024-11-05 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0008_foodmenu_unique_date_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessRebates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.CharField(default='', max_length=30)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('inactive', 'inactive'), ('active', 'active'), ('expired', 'expired'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(15)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
