# Generated by Django 5.1.1 on 2024-11-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0009_messrebates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messrebates',
            name='roll_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='messrebates',
            constraint=models.UniqueConstraint(fields=('roll_no', 'status'), name='unique_roll_status'),
        ),
    ]
