# Generated by Django 5.1.1 on 2024-11-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0011_alter_messrebates_duration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messrebates',
            name='unique_roll_status',
        ),
    ]
