# Generated by Django 5.1.4 on 2025-09-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0012_remove_messrebates_unique_roll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='food_category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner'), ('milk', 'Milk')], max_length=50),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='food_category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner'), ('milk', 'Milk')], max_length=50),
        ),
    ]
