# Generated by Django 5.1.4 on 2025-03-25 08:25

from django.db import migrations, models

def split_timestamp(apps, schema_editor):
    FoodLogModel = apps.get_model('messapp', 'FoodLog')
    for obj in FoodLogModel.objects.all():
        obj.date = obj.timestamp.date()
        obj.time = obj.timestamp.time()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0013_alter_foodlog_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RunPython(split_timestamp)
    ]
