# Generated by Django 5.1.4 on 2025-09-10 16:03

from django.db import migrations, models

def populate_date_time(apps, schema_editor):
    FoodLog = apps.get_model("messapp", "FoodLog")
    for entry in FoodLog.objects.all():
        entry.date = entry.timestamp.date()
        entry.time = entry.timestamp.time()
        entry.save(update_fields=["date", "time"])


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0013_alter_foodlog_food_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_date_time),
    ]
