# Generated by Django 5.1.4 on 2025-03-25 08:42

import messapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0014_foodlog_date_foodlog_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=messapp.models.user_profile_photo_path),
        ),
    ]
