# Generated by Django 5.1.4 on 2025-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0014_foodlog_date_foodlog_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='foodlog',
            constraint=models.UniqueConstraint(fields=('roll_no', 'food_category', 'date'), name='unique_roll_food_date'),
        ),
    ]
