# Generated by Django 5.1.4 on 2025-11-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0015_foodlog_unique_roll_food_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='menu',
            field=models.CharField(max_length=500),
        ),
    ]
