# Generated by Django 5.2.8 on 2025-11-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0015_foodlog_unique_roll_food_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
