# Generated by Django 5.2.8 on 2025-11-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0016_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='menu',
            field=models.JSONField(),
        ),
    ]
