# Generated by Django 5.1.1 on 2024-10-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('hostel', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('staff', 'Staff')], default='student', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
