# Generated by Django 5.1.1 on 2024-10-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0004_alter_foodlog_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='roll_no',
            field=models.CharField(max_length=20),
        ),
    ]
