# Generated by Django 5.1.1 on 2024-10-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0006_foodmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='food_wastage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
