# Generated by Django 5.1.1 on 2024-10-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0007_foodmenu_food_wastage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='foodmenu',
            constraint=models.UniqueConstraint(fields=('date', 'food_category'), name='unique_date_category'),
        ),
    ]
